=== lzr247/ProveraZnanja/magacin.dtd
<!ELEMENT magacin (artikal)+>
<!ELEMENT artikal (naziv,datumIzrade,cena,kompanijaProdavca,(emailProdavca)+)>

<!ELEMENT naziv (#PCDATA)>
<!ATTLIST naziv sifra ID #REQUIRED>

<!ELEMENT datumIzrade (dan,mesec,godina)>
<!ELEMENT dan (#PCDATA)>
<!ELEMENT mesec (#PCDATA)>
<!ELEMENT godina (#PCDATA)>

<!ELEMENT cena (#PCDATA)>
<!ATTLIST cena tip (dinar|evro) 'dinar'>

<!ELEMENT kompanijaProdavca (imeKompanije,(adresa)+)>
<!ELEMENT imeKompanije (#PCDATA)>
<!ELEMENT adresa (#PCDATA)>

<!ELEMENT emailProdavca (#PCDATA)>
<!ATTLIST emailProdavca tip (privatni|sluzbeni) #REQUIRED>

=== lzr247/ProveraZnanja/magacin.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE magacin SYSTEM "magacin.dtd">

<magacin xmlns="http://www.w3schools.com/"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.w3schools.com/ magacin.xsd">

<magacin>
    <artikal>

        <naziv sifra='x001'>Kokice</naziv>

        <datumIzrade>
            <dan>21</dan>
            <mesec>12</mesec>
            <godina>2012</godina>
        </datumIzrade>

        <cena tip='dinar'>50</cena>

        <kompanijaProdavca>
            <imeKompanije>Kokicar</imeKompanije>
            <adresa>Ulica Kokica 123</adresa>
            <adresa>Ulica Kokica 124</adresa>
        </kompanijaProdavca>

        <emailProdavca tip='privatni'>kokice@yahoo.com</emailProdavca>
        <emailProdavca tip='sluzbeni'>kokice2@yahoo.com</emailProdavca>

    </artikal>

    <artikal>

        <naziv sifra='x002'>Smoki</naziv>

        <datumIzrade>
            <dan>21</dan>
            <mesec>12</mesec>
            <godina>2012</godina>
        </datumIzrade>

        <cena tip='evro'>5</cena>

        <kompanijaProdavca>
            <imeKompanije>Smokiii</imeKompanije>
            <adresa>Ulica Smokija 123</adresa>
            <adresa>Ulica Smokija 124</adresa>
        </kompanijaProdavca>

        <emailProdavca tip='privatni'>smoki@yahoo.com</emailProdavca>
        <emailProdavca tip='sluzbeni'>smoki12@yahoo.com</emailProdavca>

    </artikal>

</magacin>
